baseURL = "https://groundhopping.gnatzinger.de/"
locale = "de"
defaultContentLanguage = "de"
title = "groundhopping.gnatzinger.de"

disableKinds = ["taxonomy", "term"]

[permalinks]
spiele = "/spiele/:contentbasename/"

[params]
tagline = "Ein Logbuch aller besuchten Stadien."
